import type { Metadata } from "next";
import { DM_Mono, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { WagmiProviders } from "./components/providers/wagmi";
import { AuthProvider } from "./components/providers/auth-provider";

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: ["400"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} relative ${dmMono.variable} antialiased`}
      >
        <WagmiProviders>
          <AuthProvider>
            <div className="relative z-20"> {children}</div>
          </AuthProvider>
        </WagmiProviders>
      </body>
    </html>
  );
}
